---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/usuarios/signup":
    post:
      summary: signup usuario
      tags:
      - Usuario
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
              required:
              - email
              - password
              - name
  "/usuarios/login":
    post:
      summary: login usuario
      tags:
      - Usuario
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/carritos/{id}":
    parameters:
    - name: id
      in: path
      description: id del usuario
      required: true
      schema:
        type: string
    get:
      summary: ver carrito del usuario
      security:
      - bearer_auth: []
      tags:
      - Carrito
      responses:
        '200':
          description: successful
    patch:
      summary: agregar un producto al carrito
      security:
      - bearer_auth: []
      tags:
      - Carrito
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre_producto:
                  type: string
                cantidadComprada:
                  type: integer
              required:
              - nombre_producto
              - cantidadComprada
    delete:
      summary: quitar un producto del carrito
      security:
      - bearer_auth: []
      tags:
      - Carrito
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre_producto:
                  type: string
                cantidadComprada:
                  type: number
              required:
              - nombre_producto
              - cantidadComprada
  "/carritos/comprar/{id}":
    parameters:
    - name: id
      in: path
      description: id del usuario
      required: true
      schema:
        type: string
    delete:
      summary: comprar los productos del carrito
      security:
      - bearer_auth: []
      tags:
      - Carrito
      responses:
        '200':
          description: successful
  "/compras/{id}":
    parameters:
    - name: id
      in: path
      description: id del usuario
      required: true
      schema:
        type: string
    get:
      summary: Mostrar las compras que ha hecho el usuario
      security:
      - bearer_auth: []
      tags:
      - Compras
      responses:
        '200':
          description: successful
  "/productos":
    get:
      summary: list productos
      tags:
      - Producto
      responses:
        '200':
          description: successful
    post:
      summary: create producto
      tags:
      - Producto
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/producto"
  "/productos/{id}":
    parameters:
    - name: id
      in: path
      description: id del producto
      required: true
      schema:
        type: string
    get:
      summary: show one producto
      tags:
      - Producto
      responses:
        '200':
          description: successful
    patch:
      summary: update producto
      tags:
      - Producto
      responses:
        '200':
          description: successful
    put:
      summary: update producto
      tags:
      - Producto
      responses:
        '200':
          description: successful
    delete:
      summary: delete producto
      tags:
      - Producto
      responses:
        '200':
          description: successful
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearer_format: JWT
  schemas:
    usuario:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        name:
          type: string
        carrito:
          "$ref": "#/components/schemas/carrito"
        compra:
          "$ref": "#/components/schemas/compra"
      required:
      - email
      - password
      - name
    carrito:
      type: object
      properties:
        total:
          type: number
        orders:
          type: array
          items:
            "$ref": "#/components/schemas/order"
    producto:
      type: object
      properties:
        nombre:
          type: string
        precio:
          type: number
        descripcion:
          type: string
        imagen:
          type: string
      required:
      - nombre
      - precio
      - descripcion
      - imagen
    compra:
      type: object
      properties:
        total:
          type: number
        orders:
          type: array
          items:
            "$ref": "#/components/schemas/order"
    order:
      type: object
      properties:
        total:
          type: number
        cantidad:
          type: integer
        producto:
          "$ref": "#/components/schemas/producto"
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
